# environment.yml
# Olivia Smith
# osmith@utexas.edu
# GitHub: @ossmith

name: hare-env
channels:
  - bioconda
  - conda-forge
dependencies:
  - bedtools=2.30.0
  - htslib=1.14
  - ensembl-vep=105.0
  - python=3.*
  - matplotlib
  - pandas
  - scipy
  # - r-base=4.1*
  # - r-goftest
  # - r-actuar
  # - r-fitdistrplus=1.1_11
  # - r-optparse
  - perl-bioperl=1.7.8
  - perl-dbd-mysql
  - perl-set-intervaltree
